# Generated by Django 5.0.6 on 2024-06-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('country', models.CharField(max_length=50)),
                ('event_day', models.SmallIntegerField()),
                ('event_month', models.SmallIntegerField()),
            ],
        ),
    ]
