# Generated by Django 5.0.6 on 2024-07-01 00:37

import app.models
import app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='image',
            field=models.ImageField(null=True, upload_to=app.models.image_name, validators=[app.validators.file_size]),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='country',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=models.CharField(max_length=5000, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='event_day',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='event_month',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('title', 'country')},
        ),
    ]
